# ==========================================================================
# CRE PROJECT SETTINGS — ai_prediction_mcp
# ==========================================================================

staging-settings:
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://ethereum.publicnode.com
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

production-settings:
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://ethereum.publicnode.com
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
